# Generated by Django 6.0.7 on 2026-08-07 21:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('OTHERS', 'others'), ('ELECTRONICS', 'electronics'), ('Fashion', 'fashion')], default='OTHERS', max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
