# Generated by Django 6.0 on 2025-12-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=20)),
                ('starts', models.CharField(max_length=30)),
                ('ends', models.CharField(max_length=30)),
                ('venue', models.CharField(max_length=100)),
            ],
        ),
    ]
